#!/bin/bash

# Source Variables
source ./vars &> /dev/null

# Set up path for var file so we can include it.
INCLUDE="$(dirname "$0")"

# Check for existance of jq package
if [[ ! -f /usr/bin/jq ]]
    then 
        echo
        echo "no jq package installed"
        echo "jq is needed to assign names to infra nodes during launch"
        echo
        exit
    else 
        echo "jq is installed"
fi

# Get security group id for nodes
SEC_GROUP_ID=$(aws ec2 describe-security-groups \
--query 'SecurityGroups[].GroupId[]' \
--filters Name=group-name,Values=$LOFT_SEC_GROUP \
--output text)

# Create the instances and assign tags
for NODE_COUNT in $NODE_COUNT; do
aws ec2 create-tags \
--resources `aws ec2 run-instances \
--image-id $AMI_ID \
--instance-type $LOFT_INST_TYPE \
--subnet-id $SUBNET_ID_1 \
--security-group-ids $SEC_GROUP_ID \
--key-name $KEY_NAME | jq -r ".Instances[0].InstanceId"` \
--tags "Key=Name,Value=$LOFT_NODE-$NODE_COUNT" "Key=${KEY_TAG},Value=$LOFT_TAGS"
done
