#!/bin/bash -x
source ~/cleanup-oc.sh
curl https://bootstrap.pypa.io/get-pip.py | sudo python -
sudo yum -y install gcc python-devel openssl-devel
sudo pip install virtualenv
cd ~/ && virtualenv --clear --system-site-packages ansible
source ~/ansible/bin/activate
pip install six==1.10.0 docker==2.4.2 ansible==2.3.0
git clone https://github.com/tchughesiv/catasb
cd catasb/local/linux/
git checkout aws-loft
./run_setup_local.sh
